# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/share/FMPy-master/remoting

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/share/FMPy-master/remoting

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/share/FMPy-master/remoting/CMakeFiles /root/share/FMPy-master/remoting/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/share/FMPy-master/remoting/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client_test

# Build rule for target.
client_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_test
.PHONY : client_test

# fast build rule for target.
client_test/fast:
	$(MAKE) -f CMakeFiles/client_test.dir/build.make CMakeFiles/client_test.dir/build
.PHONY : client_test/fast

#=============================================================================
# Target rules for targets named server_tcp

# Build rule for target.
server_tcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server_tcp
.PHONY : server_tcp

# fast build rule for target.
server_tcp/fast:
	$(MAKE) -f CMakeFiles/server_tcp.dir/build.make CMakeFiles/server_tcp.dir/build
.PHONY : server_tcp/fast

#=============================================================================
# Target rules for targets named client_tcp

# Build rule for target.
client_tcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_tcp
.PHONY : client_tcp

# fast build rule for target.
client_tcp/fast:
	$(MAKE) -f CMakeFiles/client_tcp.dir/build.make CMakeFiles/client_tcp.dir/build
.PHONY : client_tcp/fast

client_tcp.o: client_tcp.cpp.o

.PHONY : client_tcp.o

# target to build an object file
client_tcp.cpp.o:
	$(MAKE) -f CMakeFiles/client_tcp.dir/build.make CMakeFiles/client_tcp.dir/client_tcp.cpp.o
.PHONY : client_tcp.cpp.o

client_tcp.i: client_tcp.cpp.i

.PHONY : client_tcp.i

# target to preprocess a source file
client_tcp.cpp.i:
	$(MAKE) -f CMakeFiles/client_tcp.dir/build.make CMakeFiles/client_tcp.dir/client_tcp.cpp.i
.PHONY : client_tcp.cpp.i

client_tcp.s: client_tcp.cpp.s

.PHONY : client_tcp.s

# target to generate assembly for a file
client_tcp.cpp.s:
	$(MAKE) -f CMakeFiles/client_tcp.dir/build.make CMakeFiles/client_tcp.dir/client_tcp.cpp.s
.PHONY : client_tcp.cpp.s

client_test.o: client_test.cpp.o

.PHONY : client_test.o

# target to build an object file
client_test.cpp.o:
	$(MAKE) -f CMakeFiles/client_test.dir/build.make CMakeFiles/client_test.dir/client_test.cpp.o
.PHONY : client_test.cpp.o

client_test.i: client_test.cpp.i

.PHONY : client_test.i

# target to preprocess a source file
client_test.cpp.i:
	$(MAKE) -f CMakeFiles/client_test.dir/build.make CMakeFiles/client_test.dir/client_test.cpp.i
.PHONY : client_test.cpp.i

client_test.s: client_test.cpp.s

.PHONY : client_test.s

# target to generate assembly for a file
client_test.cpp.s:
	$(MAKE) -f CMakeFiles/client_test.dir/build.make CMakeFiles/client_test.dir/client_test.cpp.s
.PHONY : client_test.cpp.s

root/share/FMPy-master/fmpy/c-code/FMI.o: root/share/FMPy-master/fmpy/c-code/FMI.c.o

.PHONY : root/share/FMPy-master/fmpy/c-code/FMI.o

# target to build an object file
root/share/FMPy-master/fmpy/c-code/FMI.c.o:
	$(MAKE) -f CMakeFiles/server_tcp.dir/build.make CMakeFiles/server_tcp.dir/root/share/FMPy-master/fmpy/c-code/FMI.c.o
.PHONY : root/share/FMPy-master/fmpy/c-code/FMI.c.o

root/share/FMPy-master/fmpy/c-code/FMI.i: root/share/FMPy-master/fmpy/c-code/FMI.c.i

.PHONY : root/share/FMPy-master/fmpy/c-code/FMI.i

# target to preprocess a source file
root/share/FMPy-master/fmpy/c-code/FMI.c.i:
	$(MAKE) -f CMakeFiles/server_tcp.dir/build.make CMakeFiles/server_tcp.dir/root/share/FMPy-master/fmpy/c-code/FMI.c.i
.PHONY : root/share/FMPy-master/fmpy/c-code/FMI.c.i

root/share/FMPy-master/fmpy/c-code/FMI.s: root/share/FMPy-master/fmpy/c-code/FMI.c.s

.PHONY : root/share/FMPy-master/fmpy/c-code/FMI.s

# target to generate assembly for a file
root/share/FMPy-master/fmpy/c-code/FMI.c.s:
	$(MAKE) -f CMakeFiles/server_tcp.dir/build.make CMakeFiles/server_tcp.dir/root/share/FMPy-master/fmpy/c-code/FMI.c.s
.PHONY : root/share/FMPy-master/fmpy/c-code/FMI.c.s

root/share/FMPy-master/fmpy/c-code/FMI2.o: root/share/FMPy-master/fmpy/c-code/FMI2.c.o

.PHONY : root/share/FMPy-master/fmpy/c-code/FMI2.o

# target to build an object file
root/share/FMPy-master/fmpy/c-code/FMI2.c.o:
	$(MAKE) -f CMakeFiles/server_tcp.dir/build.make CMakeFiles/server_tcp.dir/root/share/FMPy-master/fmpy/c-code/FMI2.c.o
.PHONY : root/share/FMPy-master/fmpy/c-code/FMI2.c.o

root/share/FMPy-master/fmpy/c-code/FMI2.i: root/share/FMPy-master/fmpy/c-code/FMI2.c.i

.PHONY : root/share/FMPy-master/fmpy/c-code/FMI2.i

# target to preprocess a source file
root/share/FMPy-master/fmpy/c-code/FMI2.c.i:
	$(MAKE) -f CMakeFiles/server_tcp.dir/build.make CMakeFiles/server_tcp.dir/root/share/FMPy-master/fmpy/c-code/FMI2.c.i
.PHONY : root/share/FMPy-master/fmpy/c-code/FMI2.c.i

root/share/FMPy-master/fmpy/c-code/FMI2.s: root/share/FMPy-master/fmpy/c-code/FMI2.c.s

.PHONY : root/share/FMPy-master/fmpy/c-code/FMI2.s

# target to generate assembly for a file
root/share/FMPy-master/fmpy/c-code/FMI2.c.s:
	$(MAKE) -f CMakeFiles/server_tcp.dir/build.make CMakeFiles/server_tcp.dir/root/share/FMPy-master/fmpy/c-code/FMI2.c.s
.PHONY : root/share/FMPy-master/fmpy/c-code/FMI2.c.s

server_tcp.o: server_tcp.cpp.o

.PHONY : server_tcp.o

# target to build an object file
server_tcp.cpp.o:
	$(MAKE) -f CMakeFiles/server_tcp.dir/build.make CMakeFiles/server_tcp.dir/server_tcp.cpp.o
.PHONY : server_tcp.cpp.o

server_tcp.i: server_tcp.cpp.i

.PHONY : server_tcp.i

# target to preprocess a source file
server_tcp.cpp.i:
	$(MAKE) -f CMakeFiles/server_tcp.dir/build.make CMakeFiles/server_tcp.dir/server_tcp.cpp.i
.PHONY : server_tcp.cpp.i

server_tcp.s: server_tcp.cpp.s

.PHONY : server_tcp.s

# target to generate assembly for a file
server_tcp.cpp.s:
	$(MAKE) -f CMakeFiles/server_tcp.dir/build.make CMakeFiles/server_tcp.dir/server_tcp.cpp.s
.PHONY : server_tcp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... client_test"
	@echo "... server_tcp"
	@echo "... client_tcp"
	@echo "... client_tcp.o"
	@echo "... client_tcp.i"
	@echo "... client_tcp.s"
	@echo "... client_test.o"
	@echo "... client_test.i"
	@echo "... client_test.s"
	@echo "... root/share/FMPy-master/fmpy/c-code/FMI.o"
	@echo "... root/share/FMPy-master/fmpy/c-code/FMI.i"
	@echo "... root/share/FMPy-master/fmpy/c-code/FMI.s"
	@echo "... root/share/FMPy-master/fmpy/c-code/FMI2.o"
	@echo "... root/share/FMPy-master/fmpy/c-code/FMI2.i"
	@echo "... root/share/FMPy-master/fmpy/c-code/FMI2.s"
	@echo "... server_tcp.o"
	@echo "... server_tcp.i"
	@echo "... server_tcp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

